services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: jj6907**  # root 비밀번호 설정
      MYSQL_DATABASE: testdatabase
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql-container", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 30s
      retries: 5
      start_period: 5s
      timeout: 10s

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-test-app
    depends_on:
      mysql:
        condition: service_healthy  # MySQL이 준비되었을 때만 Spring Boot 앱 시작
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/testdatabase?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
      SPRING_DATASOURCE_USERNAME: testuser
      SPRING_DATASOURCE_PASSWORD: testpassword
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
