version: '3'
services:
  app:
    image: docker-test-app
    build:
      context: .
    ports:
      - "8081:8081"
    environment:
      - SPRING_SERVER_PORT=8081
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: jj6907**
      MYSQL_DATABASE: testdatabase
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3306:3306"
