CREATE TABLE IF NOT EXISTS USER_TB (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    profile_image_url VARCHAR(255),
    location VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS BODY_INFO_TB (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    inbody_image_url VARCHAR(255),
    create_date TIMESTAMP,
    deleted BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (user_id) REFERENCES USER_TB(id)
);

CREATE TABLE IF NOT EXISTS SPORTS_TB (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    deleted BOOLEAN DEFAULT FALSE
);
